events {
    worker_connections 1024;
}

http {
    upstream streamlit_cluster {
        ip_hash;
        server streamlit:8501;
    }

    server {
        listen 80;

        proxy_read_timeout    3600;
        proxy_send_timeout    3600;
        proxy_connect_timeout 60;

        proxy_buffering          on;
        proxy_buffer_size        128k;
        proxy_buffers            8 256k;
        proxy_busy_buffers_size  512k;

        location / {
            proxy_pass http://streamlit_cluster;

            proxy_http_version 1.1;
            proxy_set_header Upgrade    $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host       $host;
            proxy_set_header X-Real-IP  $remote_addr;
        }
    }
}
